### ISSUE TITLE
Arduino Nano with 328P

### ISSUE THREAD

**Issue by magnum3131** [andreobi/Jeti_ExBusSensor#1]
Hi,

Thanks for you great work, is there a way to run your Jeti_ExBusSensor with Arduino Nano on 328P processor ?

Thanks a lot
Julien

**Comment by andreobi** [comment]
Hi JulienThere are some changes necessary. 1. you have to turn off the kontronik option, Then change the usart 2 (jeti) to 12. timer changes ic3 and ic3 i.e. to measure rpm must be deleted This is what I know by handGruß Andre
-------- Ursprüngliche Nachricht --------Von: magnum3131 <notifications@github.com> Datum: 28.05.20  21:35  (GMT+01:00) An: andreobi/Jeti_ExBusSensor <Jeti_ExBusSensor@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [andreobi/Jeti_ExBusSensor] Arduino Nano with 328P (#1) 
Hi,
Thanks for you great work, is there a way to run your Jeti_ExBusSensor with Arduino Nano on 328P processor ?
Thanks a lot
Julien

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/andreobi/Jeti_ExBusSensor/issues/1",
"url": "https://github.com/andreobi/Jeti_ExBusSensor/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by andreobi** [comment]
Basicly this project uses the features of the 328PB
To run it on a basic 328P there are some changes necessary:
1. turn off the Kontronik protocoll 
2. change the exbus uart from 2 to 1 
3. change the "system" timer to another one basicly every 1ms interrupt is okay, 
   i.e. the SW usart output (OC1B) could be used instead 
4. delete the rpm measurement
5. delete the ic4 "PIN low" Message

I haven't tested it, but I thing these should be the major topics. I hope that give you a hint.

Andre
